### PR TITLE
Add clear error when SweetXML is missing

### PR DESCRIPTION
**Pull request by jfrolich**
In the docs it is not really clear you need to add the package sweet_xml in order to upload files to amazon S3. It fails with a cryptic error.

In this pull request I add a more clear error if the sweet_xml app is not loaded.

### CODE REVIEW

**Comment by jfrolich** [comment]
https://github.com/stavro/arc/issues/105

**Comment by ericmj** [comment]
Maybe this should use one of the existing exceptions in Elixir? I don't think it would be useful to match on this one in particular.

**Comment by jfrolich** [comment]
Sure, which one?

**Comment by ericmj** [comment]
I think just a `RuntimeError` which you get by default when raising without an exception: `raise "hello"`.

**Comment by benwilson512** [comment]
So, I agree that you need SweetXML to use the upload features, but that doesn't mean we want to make it mandatory for all of these lower level calls. I feel like the right place to make the check is in the upload code itself.

**Comment by venkatd** [comment]
I agree with this. I didn't have sweet_xml installed and got an error like this:

```** (MatchError) no match of right hand side value: %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InitiateMultipartUploadResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Bucket>somebucket</Bucket><Key>test-backup.sql</Key><UploadId>someuploadid</UploadId></InitiateMultipartUploadResult>", headers: [{"x-amz-id-2", "b9qT4TsjjZ+XxfnFvqqTePV8XlUZivio2qiaW9lbR6KL7wVuZ3dpmD0OVtQxQVBoIlJ/7hxdgww="}, {"x-amz-request-id", "4B8C64AC241D1DB0"}, {"Date", "Sun, 30 Oct 2016 21:05:29 GMT"}, {"Transfer-Encoding", "chunked"}, {"Server", "AmazonS3"}], status_code: 200}```

I think it would be useful to have a `RuntimeError` if `sweet_xml` isn't installed when attempting to match on/parse xml.

Thoughts?

**Comment by benwilson512** [comment]
Yup agreed. If you want to make a PR to that effect feel free!

**Comment by jfrolich** [comment]
@benwilson512: I didn't respond for some time, but just implemented your feedback in this PR.

**Pull request closed without merging**
