### PR TITLE
switch from gen stage to newly spun-off flow library

### PR DESCRIPTION
**Pull request by raorao**
see: https://elixirforum.com/t/the-future-of-genstage-and-flow/3323 for context

fix for #337

### CODE REVIEW

**Comment by benwilson512** [comment]
Hey! I appreciate the PR.

As I allude to in that issue however, I'm now thinking I would rather just use `Task.async_stream` and remove the need for `Flow` altogether. The usage of Flow in this library is incredibly simple, and it doesn't need anything more than what the 1.4 standard library offers.

If you'd like to make a PR to that affect you're more than welcome to!

**Comment by raorao** [comment]
Would you consider merging the PR as a half measure? Happy to own writing a
second PR for async_stream, but current state of the world is preventing my
project from migrating to GenStage 0.11.

**Comment by benwilson512** [comment]
>  but current state of the world is preventing my
project from migrating to GenStage 0.11

I'm not sure I understand. You can use `override: true` on the gen stage entry of your mix.exs file to force it to whatever version you like. This particular S3 function won't work sure, but everything else will. If you are using this S3 function you're best off just using your fork. I'm planning on removing the GenStage dependency prior to the next release of this library anyway.

**Comment by raorao** [comment]
hm, I couldn't get `override: true` to work, since the references to Experimental.Flow prevent the entire ex_aws application from compiling. I'll take a shot at switching ex_aws to Task.async_stream (and also migrating the entire project to 1.4), but I would still a prefer a half-measure.

**Comment by benwilson512** [comment]
Re-opening this for the moment because it's possible Flow might provide superior throughput to Task.async stream, investigating.

**Comment by benwilson512** [comment]
In the end Task.async_stream can be just as fast in this case.

**Pull request closed without merging**
