### PR TITLE
Dynamo: removed double encoding when encoding lists.

### PR DESCRIPTION
**Pull request by mr-bt**

### CODE REVIEW

**Comment by mr-bt** [comment]
The build failed... I can't run the unit tests locally either but I'm pretty sure is nothing with my commit.

**Comment by benwilson512** [comment]
The tests for the Encoder are found here: https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/dynamo/encoder_test.exs. Can you please run them locally via.
```
mix test test/lib/ex_aws/dynamo/encoder_test.exs
```

Can you elaborate a bit on your changes?

**Comment by benwilson512** [comment]
Also, the reason the tests are failing is because your branch is 10 commits behind master. Please rebase off master.

**Comment by benwilson512** [comment]
Would prefer if you would rebase instead of merge, thanks.

**Comment by mr-bt** [comment]
Sure, it makes sense. I'll cancel this PR and make another one.

**Comment by benwilson512** [comment]
Thanks, not trying to be a pain but it can help the commit history readability a lot particularly when it's a small PR.

**Pull request closed without merging**
