### PR TITLE
[WIP] Code generation

### PR DESCRIPTION
**Pull request by benwilson512**

### CODE REVIEW

**Comment by benwilson512** [comment]
Oh sweet I did in fact fix travis-ci

**Comment by benwilson512** [comment]
Also, don't click the files changed tab.

**Comment by bitwalker** [comment]
Just want to chime in and say this is awesome and I hope it gets merged, I just started working on this myself before I saw this PR.

**Comment by benwilson512** [comment]
Hey folks! It is definitely a new years priority to get some movement on this branch. Before anyone contributes however I want to take a moment and make sure that I like the overall architecture between clients/ implementation modules and such because the least year or so has provided some new ideas that might be a bit better.

I should be able to talk more specifically next week.

**Comment by benwilson512** [comment]
I'm working on this now :)

**Comment by benwilson512** [comment]
Closing this as we'll do it after the purity refactor.

**Pull request closed without merging**
