### PR TITLE
Implement Endpoints

### PR DESCRIPTION
**Pull request by adamkittelson**
There's some noise in the diff here because my sqs branch and yours have varying amounts of master merged in, but the gist here is that I've implemented and tested all the endpoint functions.

The tests in sqs_test.exs should make it easy to do any refactoring of the impl.ex functions. I've also manually integration tested them all against my AWS account in IEx so as long as the unit tests still pass after any changes they should still work in practice.

I haven't done anything with XML response parsing yet but thought this would be a good point to get my changes synced up with the primary SQS branch.

### CODE REVIEW

**Comment by adamkittelson** [comment]
Travis failures look to be lack of AWS creds, not sure if those need to be entered in travis on a branch by branch basis or something.

**Comment by benwilson512** [comment]
This is fantastic! I have to update the permissions via my IAM console. Will do that here in a bit and do a more thorough review over the weekend.

**Comment by adamkittelson** [comment]
Hope you had a good holiday weekend (assuming you're in the states). Just checking if you've had a chance to take a look at this or if you've got any questions for me on it.

**Comment by benwilson512** [comment]
Hey, would you mind merging master in again? I believe it ought to clear up the diff noise a bit.

**Comment by benwilson512** [comment]
actually, this looks really good. I'm gonna merge it into the SQS branch and then handle catching up with master there.

**Pull request merged**
