### PR TITLE
Hackney version constraints

### PR DESCRIPTION
**Pull request by hirocaster**
Congrats ver 1.0 released!! :tada:

but..... check this please. :pray:

Need `{:hackney, "~> 1.6", optional: true}` using latest version httpoison users's.
So, edit it for mix.exs in this PR.

and minor version up `hackney`.

### CODE REVIEW

**Comment by benwilson512** [comment]
Hey, thanks for the PR! Hackney 1.6.3 has known issues related to negotiating SSL connections, the lock at 1.6.1 is intentional. When Hackney sorts out those issues I'll relax the restrictions.

**Comment by hirocaster** [comment]
Thanks, reply. Could you tell me the issues's url or more info?

**Comment by benwilson512** [comment]
https://github.com/benoitc/hackney/issues/362

**Comment by hirocaster** [comment]
Thanks!! I will tracking it.

**Comment by CrowdHailer** [comment]
Just my 2 cents, but would you perhaps consider leaving this issue open until it's resolve by hackney and subsequently here.

**Comment by stocks29** [comment]
It looks like the linked issue from hackney is now closed. Maybe we can bump ex_aws to the latest version now? :)

**Comment by benwilson512** [comment]
Can someone who originally had this issue use hackney 1.6.5 and confirm that the error has done?

**Comment by kyleaa** [comment]
I'm not sure who originally had this issue, but I was able to replicate by compiling erlang in a Docker image with the `-DOPENSSL_NO_EC=1` flag set and confirmed that 1.6.3 causes a tls handshake failure while 1.6.1 and 1.6.5 work correctly.

https://github.com/kyleaa/hackney_ssl_test < Details in readme

**Comment by benwilson512** [comment]
Thank you!

**Comment by benwilson512** [comment]
Fixed in master.

**Pull request closed without merging**
