### PR TITLE
Move to pure / impure breakup

### PR DESCRIPTION
**Pull request by benwilson512**
## Services

- [x] Dynamo
- [x] S3
- [x] SNS
- [x] SQS
- [x] Kinesis
- [x] Lambda

## Other stuff

- [ ] service docs
- [ ] migration docs

### CODE REVIEW

**Comment by benwilson512** [comment]
- [ ] Kinesis get records post processing
- [ ] S3 parsing
- [ ] kinesis streaming functions.

**Comment by benwilson512** [comment]
- [ ] s3 streaming functions

**Comment by benwilson512** [comment]
- [ ] Lambda `"X-Amz-Client-Context"`

**Comment by benwilson512** [comment]
- [ ] S3 delete_all_objects

**Comment by benwilson512** [comment]
- [ ] check on `put_bucket_policy`

**Comment by ericmj** [comment]
Awesome stuff @benwilson512. Looking forward to the next version.

**Comment by benwilson512** [comment]
Thanks! I need to update basically all of the documentation, but that'll be a lot easier now. Contributing.md is gonna get a lot simpler too now.

**Pull request merged**
