### PR TITLE
[WIP] Auth v2 support for S3

### PR DESCRIPTION
**Pull request by squareduck**
Added v2 versions for auth functions. Mainly tested it with Ceph, works for me so far.
```S3_AUTH_VERSION``` config param controls this behavior.

### CODE REVIEW

**Comment by ericmj** [comment]
Why do you need auth v2?

Please avoid the timex dependency for this single thing. It's better to build the string manually.

**Comment by squareduck** [comment]
I have to work with a Ceph deployment that can't upgrade for now. There probably are other developers in the same situation with Ceph or other solutions working only with old auth v2.

I agree about Timex dependency. Will try to carve out some time to get rid of it.

**Comment by Wijnand** [comment]
Yes, we are in the same boat. We can't upgrade our object storage right now and we can't move to Amazon because the files need to be in our country for legal reasons. 

Making the old V2 auth available would help us a lot, right now we are stuck using erlcloud but I prefer to switch to ex_aws.

**Comment by benwilson512** [comment]
Hey there. I have been hesitant to support this in the bast because it is not a goal of this project to support services other than AWS, and the need for this feature comes exclusively as far as I can tell from non AWS services.

However, the signature V2 process is still an AWS process, and with that in mind I can see value in including it.

A couple of caveats:
1) @squareduck as the author of this code, I'm leaving responsibility for maintaining it with you. If someone posts an issue about the V2 signature, I'm gonna ping you.
2) AWS supports the V2 signature for more than just S3, so we need to support this fore more than just S3.
3) We are not going to include Timex. Many people prefer `Calendar` over Timex, and I'm not going to force them to choose Timex or use both. It's such a simple function we're using it for anyway, basic string interpolation will suffice.
4) We need tests.

Thanks for the PR, I'm sure it's going to be useful for a significant number of people!

**Comment by squareduck** [comment]
@benwilson512 Hey there!

1. No problem, I need this code in good working condition, so any found issues are welcome.
2. Can't personally extend the v2 auth support beyond S3. But I think S3 support is a good start. Maybe somebody who needs to use other AWS services with v2 auth will step in and implement it later on top of this PR.
3. I'll drop the timex dependency and update the PR at some point.

**Comment by benwilson512** [comment]
My point with #2 is not to ask you to do anything for any other service, but rather to point out that I don't want a PR that makes the feature explicitly just about S3.

So for example right now you have `: s3_auth_version` as a root configuration option. This will not work because the moment anyone else wants to use this with another service we're gonna get a proliferation of a dozen different root configuration versions. This belongs on configuration related to the service specifically.

Similarly with `service == :s3 && config[:s3_auth_version] == "2"` there isn't any real need to limit this explicitly to S3. I'm pretty sure that if you stored the auth version under the service config you could just do `if config[:auth_version] == "2"` and then it'd work for any service.

**Comment by benwilson512** [comment]
Closing now until it's ready.

**Comment by kanishkablack** [comment]
Any updates on this PR ?
What exactly are missing in this topic, i would like to take up the task

**Pull request closed without merging**
