### PR TITLE
[WIP] SQS Implementation

### PR DESCRIPTION
**Pull request by benwilson512**

### CODE REVIEW

**Comment by adamkittelson** [comment]
Hey Ben,

Is there anything I can do to help get this feature over the finish line?

We're starting a new project at work that will be using SQS and DynamoDB. We're using SQS in production in another project, but I just piggy-backed it on the request signing of my SimpleDB library https://github.com/adamkittelson/simplex since we only needed to hit a few of the SQS endpoints.

For our new project I'd like to use ex_aws since we're going to be using DynamoDB as well, but I'd like to avoid doing an ad-hoc SQS integration this time.

I'd be happy to contribute anything needed to get the SQS implementation squared away.

Adam

**Comment by benwilson512** [comment]
Hey, so in looking over this, there are a few changes I want to make to the typespec. I should be able to do that today or tomorrow. After that if you're willing to build out some of the Impl functions that would be greatly appreciated. Just fork the repo, and create with this branch as the upstream.

Thanks!

**Comment by adamkittelson** [comment]
Sounds good, thanks! Let me know when you're ready for me to fork.

**Comment by adamkittelson** [comment]
I was out most of last week (moving). Just wanted to check if you've had a chance to make your typespec changes so I can fork. Thanks!

**Comment by benwilson512** [comment]
Hey @adamkittelson at long last I have finally reviewed the typespec. Please feel free to offer remarks, particularly around the sending and receiving of message attributes. I haven't really used that feature in SQS much so if there's a better way to do it by all means feel free to suggest it.

**Comment by adamkittelson** [comment]
Great thanks Ben!

I haven't been using message attributes either, we've just been putting json in the message bodies, but I'll see what shakes out once I start implementing.

**Comment by benwilson512** [comment]
Awesome. Your help on this is greatly appreciated!

**Comment by benwilson512** [comment]
I think this is largely good to go. I would like to add some streaming functions in a lazy module but those can be a separate PR as they're purely additive. @adamkittelson sound good?

**Comment by adamkittelson** [comment]
Yep, the only other major thing that it's missing is XML parsing for the responses. I haven't looked at the other XML libraries currently implemented in ex_aws so I'm not sure how much of that you've been doing and how much of that has been left as an exercise for application developers, but that could be an additive PR as well.

**Comment by benwilson512** [comment]
Yup there's 2 reasons I want to leave xml parsing for a PR.

1) I've been using sweet_xml and while it's awesome, it doesn't support xml structures where portions of the structure can be missing very well (PR pending).

2) I'm hoping to be able to generating the parsing code, as it's gonna be wildly tedious otherwise.

**Comment by benwilson512** [comment]
Gonna merge this into master then, will do a release probably tomorrow.

**Comment by adamkittelson** [comment]
Sounds good, thanks Ben!

**Comment by benwilson512** [comment]
Thank you!

**Pull request merged**
