### PR TITLE
Drop dependency on httpoison, use hackney directly

### PR DESCRIPTION
**Pull request by michalmuskala**
This completely removes `HTTPoison` including the adapter. It might be desired to leave the adapter anyway, but I don't see the advantage especially since it's coming to a bigger release so some breaking may be fine.

### CODE REVIEW

**Comment by benwilson512** [comment]
Heh I'll run stuff locally, I'm very 👍  on this so no worries :)

**Comment by benwilson512** [comment]
Tests are green :)

**Comment by sashaafm** [comment]
@michalmuskala would you mind commenting on the benefits of using hackney directly? Less overhead and possible points of failure from httpoison?

**Comment by michalmuskala** [comment]
If you can avoid a dependency you should. It's yet another thing that can go wrong. 

Some dependencies are worth it, but others really aren't. I don't think httpoison adds anything significant over hackney in the most use cases. I made similar PRs to 6 projects - in most of them the whole change was basically limited to changing `HTTPoison.post` to `:hackney.post`.

**Comment by sashaafm** [comment]
Yeah that's what I was thinking. Might do the same in a couple of my projects. Thanks @michalmuskala ! :+1:

**Pull request merged**
