### PR TITLE
Added support for ECS task role credentials

### PR DESCRIPTION
**Pull request by hamstah**
Hi,

I've added support for looking up task role credentials when using ECS (taskRoleArn in the task definition) which overwrites the instance role.

Thanks

### CODE REVIEW

**Comment by hamstah** [comment]
Hey guys,
Any feedback on this?
Thanks

**Comment by benwilson512** [comment]
Hey!

This seems very useful. Could you also include some changes that mention this in the Readme?

**Comment by hamstah** [comment]
Hi Ben
Good idea, I've just updated the PR with an updated readme to cover both that change and the awscli one.

**Comment by benwilson512** [comment]
Thank you!

**Comment by hamstah** [comment]
Great thanks!

**Pull request merged**
