### PR TITLE
Add Kinesis Firehose client

### PR DESCRIPTION
**Pull request by cwc**
Refs #145 

I'm currently trying to test this to ensure that it works. I'm running the app on my dev machine, rather than within AWS, so it's choking in `ExAws.InstanceMeta.request` while trying to get IAM stuff.

My `AWS_*` environment vars are set correctly, is there something else I need to do?

### CODE REVIEW

**Comment by benwilson512** [comment]
That's odd, it should only be trying to hit the instance meta if it can't get the values from the ENV. if you open just a regular `iex` and do

```
System.get_env("AWS_ACCESS_KEY_ID")
System.get_env("AWS_SECRET_ACCESS_KEY")
```

do you see your values?

**Comment by cwc** [comment]
I'm an idiot; wrong shell :grimacing:. It seems to be working!

**Comment by cwc** [comment]
So I wasn't getting any errors, but no data was seen in my delivery streams. I poked around in the official SDK and found that the Firehose service has its own domain. Couldn't find it in the actual documentation so I was assuming it went to the same place as Kinesis, but whatever.

Latest change gets records into Firehose for sure. It might be worth looking into why no errors were emitted when it was posting to the Kinesis endpoint with invalid data.

**Comment by cwc** [comment]
Anything else needed before this can be merged?

**Comment by benwilson512** [comment]
- [ ] Basic sanity test that hits the actual API (preferably a basic list function)
- [ ] unit tests on the individual functions

**Comment by cwc** [comment]
When I send several records, I sometimes see errors logged like:

```
[error] ExAws: HTTP ERROR: :connect_timeout
[error] ExAws: HTTP ERROR: :closed
```

Is ExAws automatically retrying when this happens? Do I need to fix the Firehose client so these errors can be handled in user code?

**Comment by benwilson512** [comment]
ExAws does indeed auotmatically retry, and you do not need to worry about that yourself.

**Comment by benwilson512** [comment]
I'm happy to merge this btw the minute there are some basic tests. Please see some of the other services as examples.

**Pull request closed without merging**
