### PR TITLE
Parser for S3.upload

### PR DESCRIPTION
**Pull request by Bipsy**

### CODE REVIEW

**Comment by Bipsy** [comment]
@benwilson512 Let me know if I need to make any adjustments

**Comment by benwilson512** [comment]
Re: Your comment about the test suite from the other github issue. Just try to run the parser test you've written, if that passes it'll be fine.

**Comment by Bipsy** [comment]
@benwilson512 The parser test runs successfully. Let me know if there is anything else I can do.

**Comment by benwilson512** [comment]
Thank you!

**Pull request merged**
